name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Change to your branch if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or your preferred version

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build your project
      - name: Build project
        run: npm run build --if-present

      # 5️⃣ Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANNYS_PRO }}'
          channelId: live
          projectId: annys-pro
